server:
  servlet:
    session:
      tracking-modes: cookie
  port: 9999

spring:
  datasource:
    url: jdbc:oracle:thin:@211.38.173.250:1521:xe
    username: study_planner
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

mybatis:
  type-aliases-package: Planner.model
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:config/mybatis-config.xml